# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: full-name-splitter 0.1.3 ruby lib

Gem::Specification.new do |s|
  s.name = "full-name-splitter"
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Pavel Gorbokon", "contributors Michael S. Klishin and Trevor Creech"]
  s.date = "2015-07-30"
  s.description = ""
  s.email = "pahanix@gmail.com"
  s.extra_rdoc_files = [
    "README.mdown"
  ]
  s.files = [
    "README.mdown",
    "Rakefile",
    "VERSION",
    "features/partial_split.feature",
    "features/split.feature",
    "features/step_definitions/split_steps.rb",
    "features/support/env.rb",
    "full-name-splitter.gemspec",
    "lib/full-name-splitter.rb",
    "spec/lib/full-name-splitter_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/pahanix/full-name-splitter"
  s.rubygems_version = "2.4.6"
  s.summary = "FullNameSplitter splits full name into first and last name considering name prefixes and initials"
end

